name: Output Event details
on:
    issues:
      types: [opened, edited, closed, deleted]
jobs:
    output:
        runs-on: ubuntu-latest
        steps:
            - name: Output event details
              run: echo "${{toJson(github.event_name)}}"
